version: "3.9"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - 01_docker_compose_postgres_data:/var/lib/postgresql/data/ 
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  redis-cache:
    image: redis:6.2-alpine
    restart: always
    volumes: 
      - cache:/data
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node

  film_work-script:
    build: ./etl_process
    depends_on:
      - db
      - redis-cache
      - elasticsearch
    env_file:
      - ./.env
    environment:
        MODEL_TO_CHECK: film_work

  person-script:
    build: ./etl_process
    depends_on:
      - db
      - redis-cache
      - elasticsearch
    env_file:
      - ./.env
    environment:
        MODEL_TO_CHECK: person

  genre-script:
    build: ./etl_process
    depends_on:
      - db
      - redis-cache
      - elasticsearch
    env_file:
      - ./.env
    environment:
        MODEL_TO_CHECK: genre

volumes:
  01_docker_compose_postgres_data:
    external: true
  cache:
  elasticsearch-data: